language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - curl --version
  - composer self-update
  - composer install

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
